language: php
sudo: required
dist: xenial

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - WP_VERSION=latest WOO_VERSION=latest WP_MULTISITE=0 WP_CORE_DIR=/tmp/wordpress

# Additonal tests against stable PHP (min recommended version is 5.6) and past supported versions of WP.
matrix:
  fast_finish: true
  include:
    - name: "WooCommerce unit tests using WordPress nightly"
      php: 7.3
      env: WP_VERSION=nightly WP_MULTISITE=0 WP_CORE_DIR=/tmp/wordpress

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - phpenv config-rm xdebug.ini
  - composer config github-oauth.github.com ${GH_TOKEN}
  - composer install
  - composer global require "phpunit/phpunit=4.8.*|6.5.*"
  - bash tests/bin/install.sh woocommerce_test root '' localhost $WP_VERSION

script:
  - bash tests/bin/phpunit.sh

after_script:
  - bash tests/bin/travis.sh after