language: php

sudo: false

# Test main supported versions of PHP and HHVM against latest WP. 5.2 is min supported version.
php:
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WOO_VERSION=3.2.0-rc.1 WP_MULTISITE=0 PHP_LATEST_STABLE=7.1

# Additonal tests against stable PHP (min recommended version is 5.6) and past supported versions of WP.
matrix:
  include:
  - php: 5.6
    env: WP_VERSION=latest WOO_VERSION=3.2.0-rc.1 WP_MULTISITE=1 PHP_LATEST_STABLE=7.1

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash tests/bin/install.sh woocommerce_gzd_test root '' localhost $WP_VERSION $WOO_VERSION
  - bash tests/bin/travis.sh before

script:
  - bash tests/bin/phpunit.sh
  - bash tests/bin/travis.sh during

after_script:
  - bash tests/bin/travis.sh after